package com.qaprosoft.argon.dbaccess.dao;

import com.qaprosoft.argon.dbaccess.dao.mysql.BlacklistDAO;
import com.qaprosoft.argon.dbaccess.dao.mysql.ChatDAO;
import com.qaprosoft.argon.dbaccess.dao.mysql.StatusDAO;
import com.qaprosoft.argon.dbaccess.dao.mysql.UserDAO;
import com.qaprosoft.argon.dbaccess.utils.KeyGenerator;
import com.qaprosoft.argon.models.db.*;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.Arrays;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertNotEquals;
import static org.testng.Assert.assertNull;

/**
 * @author kbugrim
 * @since 10 Dec 2017
 */
@Test
@ContextConfiguration("classpath:com/qaprosoft/argon/dbaccess/dbaccess-test.xml")
public class BlacklistDAOTest extends AbstractTestNGSpringContextTests {

    private static final boolean ENABLED = false;

    @Autowired
    private BlacklistDAO blacklistDAO;

    @Autowired
    private UserDAO userDAO;

    @Autowired
    private ChatDAO chatDAO;

    @Autowired
    private StatusDAO statusDAO;

    private static final Blacklist BLACKLIST = new Blacklist();
    {
        BLACKLIST.setChat(CHAT);
        BLACKLIST.setUser(USER1);
    }

    private final static User USER1 = new User();
    {
        USER1.setEmail(KeyGenerator.getKey() + "@test-mail.com");
        USER1.setEnabled(true);
        USER1.setFirstName("Boris");
        USER1.setLastName("The Blade");
        USER1.setPassword("pass" + KeyGenerator.getKey().toString());
        USER1.setDob(DateTime.now().withTime(0, 0, 0, 0).minusYears(18).toDate());
        USER1.setUsername("user1" + KeyGenerator.getKey());
        USER1.setVerified(true);
    }

    private final static User USER2 = new User();
    {
        USER2.setEmail(KeyGenerator.getKey() + "@test-mail.com");
        USER2.setEnabled(true);
        USER2.setFirstName("Ivan");
        USER2.setLastName("Ivanov");
        USER2.setPassword("pass" + KeyGenerator.getKey().toString());
        USER2.setDob(DateTime.now().withTime(0, 0, 0, 0).minusYears(18).toDate());
        USER2.setUsername("user2" + KeyGenerator.getKey());
        USER2.setVerified(true);
    }

    private static final Chat CHAT = new Chat();
    {
        CHAT.setName("chat" + KeyGenerator.getKey());
        CHAT.setUsers(Arrays.asList(USER2));
    }

    @BeforeClass
    public void init(){
        USER1.setStatus(statusDAO.getStatusByType(Status.Type.OFFLINE));
        USER2.setStatus(statusDAO.getStatusByType(Status.Type.OFFLINE));
        userDAO.createUser(USER1);
        userDAO.createUser(USER2);
        chatDAO.createChat(CHAT);
        chatDAO.addUserToChat(USER1.getId(), CHAT.getId());
        chatDAO.addUserToChat(USER2.getId(), CHAT.getId());
    }

    @AfterClass
    public void delete(){
        chatDAO.removeUserFromChat(USER1.getId(),CHAT.getId());
        chatDAO.removeUserFromChat(USER2.getId(),CHAT.getId());
        chatDAO.deleteChatById(CHAT.getId());
        userDAO.deleteUserById(USER1.getId());
        userDAO.deleteUserById(USER2.getId());
    }

    @Test(enabled = ENABLED)
    public void createBlacklist()
    {
        blacklistDAO.createBlacklist(BLACKLIST);
        assertNotEquals(BLACKLIST.getId(), 0, "Blacklist ID must be set up by autogenerated keys.");
    }

    @Test(enabled = ENABLED, dependsOnMethods = {"createBlacklist"})
    public void getBlacklistById()
    {
        checkBlacklist(blacklistDAO.getBlacklistById(BLACKLIST.getId()));
    }

    @Test(enabled = ENABLED, dependsOnMethods = {"createBlacklist","getBlacklistById"})
    public void updateBlacklist()
    {
        USER1.setFirstName("Ivan");
        USER1.setLastName("Ivanov");
        CHAT.setName("New name");
        userDAO.updateUser(USER1);
        chatDAO.updateChat(CHAT);
        blacklistDAO.updateBlacklist(BLACKLIST);
        checkBlacklist(blacklistDAO.getBlacklistById(BLACKLIST.getId()));
    }

    @Test(enabled = ENABLED, dependsOnMethods =
            { "createBlacklist","getBlacklistById","updateBlacklist"})
    public void deleteBlacklistById()
    {
        blacklistDAO.deleteBlacklistById(BLACKLIST.getId());
        assertNull(blacklistDAO.getBlacklistById(BLACKLIST.getId()));
    }

    private void checkBlacklist(Blacklist blacklist)
    {
        assertEquals(blacklist.getUser().getFirstName(), BLACKLIST.getUser().getFirstName(), "Blacklist user is not as expected.");
        assertEquals(blacklist.getUser().getLastName(), BLACKLIST.getUser().getLastName(), "Blacklist user is not as expected.");
        assertEquals(blacklist.getChat().getName(), BLACKLIST.getChat().getName(), "Blacklist chat is not as expected.");
    }
}
