package com.qaprosoft.argon.dbaccess.dao;

import com.qaprosoft.argon.dbaccess.dao.mysql.BlacklistDAO;
import com.qaprosoft.argon.dbaccess.dao.mysql.ChatDAO;
import com.qaprosoft.argon.dbaccess.dao.mysql.StatusDAO;
import com.qaprosoft.argon.dbaccess.dao.mysql.UserDAO;
import com.qaprosoft.argon.dbaccess.utils.KeyGenerator;
import com.qaprosoft.argon.models.db.*;
import org.joda.time.DateTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.testng.AbstractTestNGSpringContextTests;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import static org.testng.Assert.assertNotEquals;
import static org.testng.Assert.assertNull;

/**
 * @author kbugrim
 * @since 10 Dec 2017
 */
@Test
@ContextConfiguration("classpath:com/qaprosoft/argon/dbaccess/dbaccess-test.xml")
public class BlacklistDAOTest extends AbstractTestNGSpringContextTests {

    private static final boolean ENABLED = true;

    @Autowired
    private BlacklistDAO blacklistDAO;

    @Autowired
    private UserDAO userDAO;

    @Autowired
    private ChatDAO chatDAO;

    @Autowired
    private StatusDAO statusDAO;

    private static final Blacklist BLACKLIST = new Blacklist();
    {
        BLACKLIST.setChat(CHAT);
        BLACKLIST.setUser(USER);
    }

    private static final Chat CHAT = new Chat();
    {
        CHAT.setName("chat" + KeyGenerator.getKey());
    }

    private static final Status STATUS = new Status();
    {
        STATUS.setStatusType(Status.StatusType.TEST_OFLINE);
    }

    private final static User USER = new User();
    {
        USER.setEmail(KeyGenerator.getKey() + "@test-mail.com");
        USER.setEnabled(true);
        USER.setFirstName("Boris");
        USER.setLastName("The Blade");
        USER.setPassword("pass" + KeyGenerator.getKey().toString());
        USER.setDob(DateTime.now().withTime(0, 0, 0, 0).minusYears(18).toDate());
        USER.setUsername("user" + KeyGenerator.getKey());
        USER.setVerified(true);
        USER.setStatus(STATUS);
    }


    @BeforeClass
    public void init(){
        statusDAO.createStatus(STATUS);
        chatDAO.createChat(CHAT);
        userDAO.createUser(USER);
    }

    @AfterClass
    public void delete(){
        userDAO.deleteUserById(USER.getId());
        chatDAO.deleteChatById(CHAT.getId());
        statusDAO.deleteStatusById(CHAT.getId());
    }

    @Test(enabled = ENABLED)
    public void createBlacklist()
    {
        blacklistDAO.createBlacklist(BLACKLIST);
        assertNotEquals(BLACKLIST.getId(), 0, "Blacklist ID must be set up by autogenerated keys.");
    }

    @Test(enabled = ENABLED, dependsOnMethods =
            { "createBlacklist"})
    public void deleteBlacklistById()
    {
        blacklistDAO.deleteBlacklistById(BLACKLIST.getId());
        assertNull(blacklistDAO.getBlacklistById(BLACKLIST.getId()));
    }
}
