INSERT INTO `argon`.`AUTHORITIES` (`ID`, `AUTHORITY`) VALUES ('1', 'ADMIN');
INSERT INTO `argon`.`AUTHORITIES` (`ID`, `AUTHORITY`) VALUES ('2', 'USER');

INSERT INTO `argon`.`STATUSES` (`ID`, `STATUS`) VALUES ('1', 'ONLINE');
INSERT INTO `argon`.`STATUSES` (`ID`, `STATUS`) VALUES ('2', 'OFFLINE');
